FROM php:8.5-fpm

RUN set -eux; \
    apt update; \
    apt install -y \
        git \
        unzip \
        libicu-dev \
        libpq-dev \
        libzip-dev \
    ; \
    docker-php-ext-install zip pdo_mysql; \
    apt clean; \
    rm -rf /var/lib/apt/lists/*

# Install Xdebug
RUN pecl install xdebug \
    && docker-php-ext-enable xdebug

# Create initial xdebug config (disabled by default)
RUN echo ";zend_extension=xdebug.so" > /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /var/www

EXPOSE 9000
CMD ["php-fpm"]

