services:
  db:
    image: mysql:8.0
    container_name: ptb_db
    restart: always
    environment:
      MYSQL_DATABASE: bundle_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: bundle_user
      MYSQL_PASSWORD: bundle_password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  php:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: ptb_php
    working_dir: /var/www
    volumes:
      - ./:/var/www/
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: ptb_nginx
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - php

  mailer:
    image: axllent/mailpit
    container_name: ptb_mailer
    ports:
      - "1026:1025"
      - "8026:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

volumes:
  db_data:

