api_controllers:
    resource:
        path: ../src/Api/Controller/
        namespace: VanDerSangen\ProjectTemplateBundle\Api\Controller
    type: attribute

user_controllers:
    resource:
        path: ../src/User/Controller/
        namespace: VanDerSangen\ProjectTemplateBundle\User\Controller
    type: attribute

auth_controllers:
    resource:
        path: ../src/Auth/Controller/
        namespace: VanDerSangen\ProjectTemplateBundle\Auth\Controller
    type: attribute

cron_controllers:
    resource:
        path: ../src/Cron/Controller/
        namespace: VanDerSangen\ProjectTemplateBundle\Cron\Controller
    type: attribute

super_admin_controllers:
    resource:
        path: ../src/SuperAdmin/Controller/
        namespace: VanDerSangen\ProjectTemplateBundle\SuperAdmin\Controller
    type: attribute

payment_controllers:
    resource:
        path: ../src/Payment/Controller/
        namespace: VanDerSangen\ProjectTemplateBundle\Payment\Controller
    type: attribute

tenant_controllers:
    resource:
        path: ../src/Tenant/Controller/
        namespace: VanDerSangen\ProjectTemplateBundle\Tenant\Controller
    type: attribute


shopify_controllers:
    resource:
        path: ../src/Shopify/Controller/
        namespace: VanDerSangen\ProjectTemplateBundle\Shopify\Controller
    type: attribute
